BHIP_TIMESTAMP_FILE =./app/timestamp_autogenerated.h

PROJECT_NAME=u204
PROJECT_VERSION=3.0.0
PROJECT_DATA=2022-12-8
PROJECT_TIME=18:00:00

$(PROJECT_NAME)_prj:
	@echo \#  
	@echo \# Compiling project $(PROJECT_NAME) transcode..... 
	@echo \#
	@echo \# Step 1: hi_common.....
	echo "#define BH_SOFTWARE_VERSION \"$(PROJECT_VERSION)\"" > $(BHIP_TIMESTAMP_FILE)
	echo "#define BH_SOFTWARE_DATE \"$(PROJECT_DATA)\"" >> $(BHIP_TIMESTAMP_FILE)
	echo "#define BH_SOFTWARE_TIME \"$(PROJECT_TIME)\"" >> $(BHIP_TIMESTAMP_FILE)
	#make hi_common_build TARGET=env
	#make hi_common_build TARGET=lib
	
	@echo \#
	@echo \# Step 2: bh_$(PROJECT_NAME)_app.....
	make app_build TARGET=env
	make app_build TARGET=lib
	make app_build TARGET=exe
	make app_build TARGET=strip

app_build:
	make -j4 -C ./app MODULE=m_$(PROJECT_NAME)_app PROJECT_NAME=$(PROJECT_NAME) MODULE_ROOT=$(shell pwd) $(TARGET)

clean:
	@echo \#  
	@echo \# cleaning project $(PROJECT_NAME)..... 
	@echo \#
	make app_build TARGET=clean

all: clean $(PROJECT_NAME)_prj