include ../common_header_a8.mk

PUD_DIR=../../../pub
MODULE_INCLUDE = $(CFG_INC)  -I../include

MODULE_LIBS    = $(MODULE_LIB_DIR)/m_$(PROJECT_NAME)_app.a 
MODULE_LIBS    += $(MODULE_LIB_DIR)/rockchip/libosal.a
MODULE_LIBS    += $(MODULE_LIB_DIR)/rockchip/libutils.a

include ../common_footer_a8.mk


