/************************************************************************
 *FileName:  Process_global.h
 *Author:    Jin Qiuyu
 *Version:   2.0
 *Date:      2020-03-08
 *Description: 应用层-全局依赖头文件
 ************************************************************************/
#ifndef _PROCESS_GLOBAL
#define _PROCESS_GLOBAL

#include "timestamp_autogenerated.h"

#include "Interface_Com.h"
#include "Interface_Udp.h"
#include "Interface_PCIE.h"

#include "Midware_GPIO.h"
#include "Midware_Fifo.h"
#include "Midware_Supplement.h"
#include "Midware_Logcplus.h"

//宏定义区//

#define SELF_TEST (1)

#define MAX_VIS_BIG_VIDEO  (10)

#define MAX_CMP_PACK_LENGTH  (64*61440)

#define CMP_PACK_LENGTH  (61440)
#define CMP_PACK_LENGTH_F  (61440.0F)

//结构体申明//

struct img_pack
{
	img_pack(unsigned int buffer_lens)
	{
		n_length = buffer_lens;
		p_buf = new unsigned char[buffer_lens];
	}

	~img_pack()
	{
		if (p_buf != NULL)
		{
			delete[]p_buf;
			p_buf = NULL;
		}
	}

	unsigned char * p_buf;
	unsigned int  n_length;
};

struct stream_pack
{
	stream_pack()
	{
		n_length = 0;
		p_buf = new unsigned char[MAX_CMP_PACK_LENGTH];
	}

	~stream_pack()
	{
		if (p_buf != NULL)
		{
			delete[]p_buf;
			p_buf = NULL;
		}
	}

	unsigned char * p_buf;
	unsigned int  n_length;
};

struct cmp_send_protocol
{
	unsigned char cmp_head_1;//信息单元标识0xEE//
	unsigned char cmp_head_2;//信息单元标识0x16//

	unsigned short cmp_pack_count;
	unsigned short cmp_pack_num;
	unsigned short cmp_length_now;

	unsigned char cmp_data[CMP_PACK_LENGTH];
};

//全局变量申明//

extern int flag_end;

extern FIFO<img_pack *> queue_img_src_to_vpss;
extern FIFO<img_pack *> queue_img_src_to_tracker;

extern FIFO<stream_pack *> queue_stream_to_out;

extern CUdp * m_udp_p2p;
extern CCom * m_com_p2p;
extern CPCIE * m_pcie_p2p;

extern int n_BitRate_global;
extern int roi_1,roi_2,roi_3,roi_4;
extern bool b_track_init;
#endif//_PROCESS_GLOBAL

